version: "3.8"
services:
  apache:
    image: php:8.2.14-apache
    volumes:
      - ./:/var/www/html/
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`php.dimaspadma.my.id`)"
      - "traefik.http.routers.php.entrypoints=websecure"
      - "traefik.http.routers.php.tls.certresolver=myresolver"

networks:
  proxy:
    external: true